team1_name = input("Enter the name of Team 1: ")
team1_score = input("Enter the score of Team 1: ")
team1_overs = input("Enter the overs played by Team 1: ")
team2_name = input("Enter the name of Team 2: ")
team2_score = input("Enter the score of Team 2: ")
team2_overs = input("Enter the overs played by Team 2: ")
print(f'Match Details:\n{team1_name} scored {team1_score} in {team1_overs} overs.\n{team2_name} scored {team2_score} in {team2_overs} overs.')
